# Generated by Django 4.1.7 on 2023-04-21 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_userprofile_cover_pic_userprofile_cover_pic1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='cover_pic1',
            new_name='cover_pic',
        ),
    ]
