# Generated by Django 4.1.7 on 2023-04-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_cover_pic1_userprofile_cover_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cover_pic',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cover_pic1',
            field=models.ImageField(blank=True, default='/profilepics/cover1.jpg', upload_to='coverpic'),
        ),
    ]
